import type {
  Account,
  Program,
  VolunteerRegistration,
  Certificate,
  ChatMessage,
  OrganizationRegistration,
} from "./types"

export const mockAccounts: Account[] = [
  {
    id: "vol-001",
    name: "Nguyễn Văn A",
    email: "nguyenvana@email.com",
    phone: "0901234567",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Passionate about helping the community",
    createdAt: "2024-01-15",
  },
  {
    id: "vol-002",
    name: "Trần Thị B",
    email: "tranthib@email.com",
    phone: "0912345678",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Love working with children",
    createdAt: "2024-02-20",
  },
  {
    id: "vol-003",
    name: "Lê Văn C",
    email: "levanc@email.com",
    phone: "0923456789",
    role: "volunteer",
    avatar: "/volunteer-avatar.png",
    bio: "Environmental advocate",
    createdAt: "2024-03-10",
  },
  {
    id: "org-001",
    name: "Tổ chức Từ Tâm",
    email: "contact@tutam.org",
    phone: "0288888888",
    role: "organization",
    avatar: "/generic-organization-logo.png",
    bio: "Helping underprivileged children",
    createdAt: "2023-06-01",
  },
  {
    id: "org-002",
    name: "Xanh Việt",
    email: "info@xanhviet.org",
    phone: "0289999999",
    role: "organization",
    avatar: "/generic-organization-logo.png",
    bio: "Environmental protection organization",
    createdAt: "2023-08-15",
  },
  {
    id: "admin-001",
    name: "Admin System",
    email: "admin@together.vn",
    phone: "0287777777",
    role: "admin",
    createdAt: "2023-01-01",
  },
]

export const mockPrograms: Program[] = [
  {
    id: "prog-001",
    name: "Dạy kèm cho trẻ em vùng sâu",
    description: "Giúp trẻ em vùng sâu vùng xa có cơ hội học tập tốt hơn thông qua các buổi dạy kèm miễn phí",
    domesticDescription: "Chương trình dạy kèm miễn phí cho trẻ em vùng sâu vùng xa tại Việt Nam",
    isInternational: false,
    organizationId: "org-001",
    organizationName: "Tổ chức Từ Tâm",
    category: "Giáo dục",
    location: "Hà Nội",
    startDate: "2024-04-01",
    endDate: "2024-12-31",
    duration: "9 tháng",
    schedule: ["Thứ 2", "Thứ 4", "Thứ 6"],
    timeSlots: "14:00 - 17:00",
    volunteersNeeded: 20,
    volunteersJoined: 12,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-002",
    name: "Trồng cây xanh cho thành phố",
    description: "Cùng nhau trồng cây xanh để bảo vệ môi trường và làm đẹp thành phố",
    domesticDescription: "Hoạt động trồng cây xanh tại các khu vực công cộng trong thành phố",
    isInternational: false,
    organizationId: "org-002",
    organizationName: "Xanh Việt",
    category: "Môi trường",
    location: "TP. Hồ Chí Minh",
    startDate: "2024-05-01",
    endDate: "2024-11-30",
    duration: "7 tháng",
    schedule: ["Chủ nhật đầu tiên mỗi tháng"],
    timeSlots: "06:00 - 09:00",
    volunteersNeeded: 50,
    volunteersJoined: 35,
    image: "/planting-trees.png",
    status: "active",
  },
  {
    id: "prog-003",
    name: "Chăm sóc người già cô đơn",
    description: "Đến thăm và chăm sóc những người già cô đơn, mang lại niềm vui cho họ",
    domesticDescription: "Chương trình thăm hỏi và chăm sóc người cao tuổi cô đơn tại Việt Nam",
    isInternational: false,
    organizationId: "org-001",
    organizationName: "Tổ chức Từ Tâm",
    category: "Y tế",
    location: "Hà Nội",
    startDate: "2024-03-15",
    endDate: "2024-12-31",
    volunteersNeeded: 15,
    volunteersJoined: 8,
    image: "/elderly-care-support.png",
    status: "active",
  },
  {
    id: "prog-004",
    name: "Dọn dẹp bãi biển",
    description: "Tham gia dọn dẹp bãi biển để bảo vệ hệ sinh thái biển",
    domesticDescription: "Hoạt động dọn dẹp rác thải tại các bãi biển Việt Nam",
    isInternational: false,
    organizationId: "org-002",
    organizationName: "Xanh Việt",
    category: "Môi trường",
    location: "Đà Nẵng",
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    volunteersNeeded: 30,
    volunteersJoined: 28,
    image: "/beach-cleanup.png",
    status: "active",
  },
  {
    id: "prog-005",
    name: "Sáng kiến Giáo dục Toàn cầu",
    description: "Chương trình tình nguyện quốc tế hỗ trợ giáo dục tại các nước đang phát triển",
    domesticDescription: "Chương trình giáo dục quốc tế hỗ trợ trẻ em tại các nước đang phát triển",
    internationalDescription: "Tham gia cùng đội ngũ quốc tế của chúng tôi để cung cấp hỗ trợ giáo dục và tài nguyên cho trẻ em tại các nước đang phát triển ở Đông Nam Á",
    isInternational: true,
    organizationId: "org-001",
    organizationName: "Tổ chức Từ Tâm",
    category: "Giáo dục",
    location: "Thái Lan, Campuchia, Lào",
    startDate: "2024-07-01",
    endDate: "2024-12-31",
    volunteersNeeded: 25,
    volunteersJoined: 18,
    image: "/teaching-children.jpg",
    status: "active",
  },
  {
    id: "prog-006",
    name: "Bảo tồn Môi trường Quốc tế",
    description: "Nỗ lực bảo vệ và bảo tồn môi trường xuyên biên giới",
    domesticDescription: "Chương trình bảo vệ môi trường xuyên biên giới",
    internationalDescription: "Tham gia các dự án bảo tồn môi trường quốc tế trên nhiều quốc gia trong khu vực",
    isInternational: true,
    organizationId: "org-002",
    organizationName: "Xanh Việt",
    category: "Môi trường",
    location: "Việt Nam, Thái Lan, Malaysia",
    startDate: "2024-08-01",
    endDate: "2025-02-28",
    volunteersNeeded: 40,
    volunteersJoined: 22,
    image: "/planting-trees.png",
    status: "active",
  },
]

export const mockRegistrations: VolunteerRegistration[] = [
  {
    id: "reg-001",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-001",
    programName: "Dạy kèm cho trẻ em vùng sâu",
    status: "approved",
    appliedDate: "2024-03-20",
    approvedDate: "2024-03-22",
    hoursContributed: 24,
  },
  {
    id: "reg-002",
    volunteerId: "vol-002",
    volunteerName: "Trần Thị B",
    programId: "prog-002",
    programName: "Trồng cây xanh cho thành phố",
    status: "pending",
    appliedDate: "2024-04-10",
  },
  {
    id: "reg-003",
    volunteerId: "vol-003",
    volunteerName: "Lê Văn C",
    programId: "prog-002",
    programName: "Trồng cây xanh cho thành phố",
    status: "approved",
    appliedDate: "2024-04-05",
    approvedDate: "2024-04-07",
    hoursContributed: 16,
  },
  {
    id: "reg-004",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-003",
    programName: "Chăm sóc người già cô đơn",
    status: "approved",
    appliedDate: "2024-02-28",
    approvedDate: "2024-03-01",
    hoursContributed: 32,
  },
  {
    id: "reg-005",
    volunteerId: "vol-002",
    volunteerName: "Trần Thị B",
    programId: "prog-001",
    programName: "Dạy kèm cho trẻ em vùng sâu",
    status: "approved",
    appliedDate: "2024-03-25",
    approvedDate: "2024-03-27",
    hoursContributed: 18,
  },
]

export const mockCertificates: Certificate[] = [
  {
    id: "cert-001",
    volunteerId: "vol-001",
    volunteerName: "Nguyễn Văn A",
    programId: "prog-001",
    programName: "Dạy kèm cho trẻ em vùng sâu",
    hoursContributed: 24,
    issuedDate: "2024-04-15",
    certificateNumber: "CERT-2024-001",
  },
  {
    id: "cert-002",
    volunteerId: "vol-003",
    volunteerName: "Lê Văn C",
    programId: "prog-002",
    programName: "Trồng cây xanh cho thành phố",
    hoursContributed: 16,
    issuedDate: "2024-05-20",
    certificateNumber: "CERT-2024-002",
  },
]

export const mockOrganizationRegistrations: OrganizationRegistration[] = [
  {
    id: "org-reg-001",
    organizationName: "Tổ chức Giáo dục Xanh",
    email: "contact@giaoduc-xanh.org",
    phone: "0291111111",
    bio: "Tổ chức tập trung vào giáo dục bền vững cho trẻ em",
    status: "pending",
    appliedDate: "2024-10-15",
  },
  {
    id: "org-reg-002",
    organizationName: "Quỹ Hỗ trợ Cộng đồng",
    email: "support@community-fund.org",
    phone: "0292222222",
    bio: "Hỗ trợ các dự án cộng đồng và phát triển bền vững",
    status: "pending",
    appliedDate: "2024-10-18",
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Từ Tâm",
    userRole: "organization",
    message: "Chào các bạn tình nguyện viên! Chúng tôi rất vui khi có các bạn tham gia chương trình này.",
    timestamp: "2024-04-01T08:00:00",
  },
  {
    id: "msg-002",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Từ Tâm",
    userRole: "organization",
    message: "Buổi dạy kèm hôm nay lúc 14:00 tại trường tiểu học Nguyễn Huệ. Các bạn chuẩn bị sẵn sàng nhé!",
    timestamp: "2024-04-01T11:00:00",
  },
  {
    id: "msg-003",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Từ Tâm",
    userRole: "organization",
    message: "Cảm ơn các bạn đã tham gia buổi dạy kèm hôm nay. Các em học sinh rất vui và tiến bộ nhiều!",
    timestamp: "2024-04-01T16:30:00",
  },
  {
    id: "msg-004",
    programId: "prog-001",
    userId: "org-001",
    userName: "Tổ chức Từ Tâm",
    userRole: "organization",
    message: "Tuần tới chúng ta sẽ có buổi dạy kèm đặc biệt với chủ đề 'Khoa học vui'. Các bạn chuẩn bị một số thí nghiệm đơn giản nhé!",
    timestamp: "2024-04-02T09:15:00",
  },
  {
    id: "msg-005",
    programId: "prog-002",
    userId: "org-002",
    userName: "Xanh Việt",
    userRole: "organization",
    message: "Chào mừng các bạn đến với chương trình trồng cây xanh! Chúng ta sẽ bắt đầu từ 7:00 sáng ngày mai.",
    timestamp: "2024-05-01T09:00:00",
  },
  {
    id: "msg-006",
    programId: "prog-002",
    userId: "org-002",
    userName: "Xanh Việt",
    userRole: "organization",
    message: "Nhớ mang theo nước uống và mũ nón. Chúng ta sẽ trồng cây tại công viên Lê Văn Tám.",
    timestamp: "2024-05-01T14:20:00",
  },
  {
    id: "msg-007",
    programId: "prog-003",
    userId: "org-001",
    userName: "Tổ chức Từ Tâm",
    userRole: "organization",
    message: "Cảm ơn các bạn đã tham gia chương trình chăm sóc người già. Hãy mang theo tinh thần yêu thương và sự kiên nhẫn.",
    timestamp: "2024-03-15T10:00:00",
  },
]
